-d E:\fbga\tek_port_RAM\impl\gwsynthesis\tek_port_RAM.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cfg E:\fbga\tek_port_RAM\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
